# 上传基础URL
upload-base-url: "https://www.sencraft.top/fawe"
# 临时文件夹
temp-folder: "temp_world_downloads"
# 上传超时时间(毫秒)
upload-timeout: 300000
# 最大文件大小 (字节) - 默认1GB
max-file-size: 1073741824
# 上传限速 (字节/秒) - 0表示不限速
# 例如: 1048576 = 1MB/s, 5242880 = 5MB/s
upload-speed-limit: 0

# 消息配置
messages:
  plugin-enabled: "WorldDownloadPlugin 已启用!"
  plugin-disabled: "WorldDownloadPlugin 已禁用!"
  player-only: "§c这个命令只能由玩家执行!"
  usage: "§c用法: /worlddownload <世界名称>"
  permission-hint: "§e提示: 你需要拥有对应权限才能下载世界"
  no-permission: "§c你没有权限下载这个世界: {world}"
  permission-required: "§e所需权限: worlddownload.download.{world}"
  wildcard-permission: "§7或者通配符权限: worlddownload.download.*"
  world-not-exist: "§c世界不存在: {world}"
  start-download: "§a开始下载世界: {world}"
  compressing: "§e正在压缩世界文件..."
  uploading: "§e正在上传到服务器... 文件大小: {size}MB"
  upload-success: "§a世界上传成功!"
  upload-failed: "§c上传失败，请联系管理员!"
  file-too-large: "§c文件太大，无法上传! 最大允许: {size}MB"
  upload-error: "§c上传过程中发生错误: {error}"
  available-worlds: "§6服务器中的世界:"
  world-list-item: "§a  • {world}"
  world-list-item-no-perm: "§c  • {world} (无权限)"
  upload-progress: "§e正在上传到: {url}"
  response-code: "§7上传响应码: {code}"
  redirect-url: "§7重定向到: {url}"
  default-download-url: "§7构造默认URL: {url}"
  download-link: "§b下载链接: {url}"
  temp-file-cleanup: "§7临时文件已清理"
  upload-speed-limit: "§7上传限速: {speed} KB/s"
  upload-progress-detail: "§7上传进度: {progress}% ({uploaded}/{total} MB)"
