name: WorldDownloadPlugin
version: 1.1
main: io.github.sensen1234.worldDownload.WorldDownloadPlugin
api-version: 1.21
author: sensen1234
commands:
  worlddownload:
    description: Download a world
    usage: /worlddownload <worldname>
    permission: worlddownload.use
permissions:
  worlddownload.use:
    description: Allows using the world download command
    default: true
  worlddownload.download.*:
    description: Allows downloading all worlds
    default: op
